import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./styles/style.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Watch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="timefoter">
          <div className="stopwatch">
            <button className="btn">
              <Link className="link1" href="/stopwatch">
                <span className="material-symbols-outlined">timer</span>
                <h1>StopWatch</h1>
              </Link>
            </button>
          </div>
          <div className="Timer">
            <button className="btns">
              <Link href="/" className="link2">
                <span className="material-symbols-outlined">pace</span>
                <h1>Timer</h1>
              </Link>
            </button>
          </div>
        </div>
      </body>
    </html>
  );
}
